<!doctype html>
<html lang="en">
<head>
    <?php echo $this->headTitle(); ?>
<!--    --><?php //echo $this->headMeta();?>
    <?php echo $this->headLink();?>
<!--    <script src="--><?php //echo STATIC_URL; ?><!--/js/libs/autobahn/autobahn.min.js"></script>-->
    <script src="https://cdn.jsdelivr.net/autobahnjs/0.11.2/autobahn.min.js"></script>
</head>
<body>
    aaaaaaaaaaaaaa
</body>

<script>
//    var connection = new autobahn.Connection({url: 'ws://ws-db.adxdev.vn/', realm: 'insight:fe'});
//    var connection = new autobahn.Connection({url: 'ws://ws-db.adxdev.vn/', realm: 'insight:fe'});
    var connection = new autobahn.Connection({url: 'ws://127.0.0.1:8888/', realm: 'insight:fe'});
    connection.onopen = function (session) {
        // 4) call a remote procedure
        var argument = [
            {
                'user_id': '1600000355',
                'time_type' : 'm',
                'start_time' : '',
                'time_span' : '59',
                'site_ids' : ['512041970'],
                'metrics' : ['page_view', 'visitor'],
                'network_id' : '22773',
                'limit' : 10,
                'order_by' : 'page_view',
                'is_group_by_dim' : true,
                'sub_dimension' : [
                    'gender' , 'topic' , 'age'
                ]
            }
        ];
        session.call('audience_data_top_age', argument).then(
            function (res) {
                console.log("Result:", res);
            }
        );
    };

    connection.open();
</script>
</html>

